### PR TITLE
SG-22646-shotgrid Shotgun instances has been replaced

### PR DESCRIPTION
**Pull request by zamu5**

### CODE REVIEW

**Review by jfboismenu — APPROVED** [review]
Looks good to me.

**Review by mathurf — COMMENTED** [review]
Should we update the support URL in this PR?
image

**Comment by jfboismenu** [comment]
tk-core provides this value. Unfortunately I don't know what the final URL will be yet. Once I get clarification on that I'll update tk-core accordingly.

**Review by mathurf — APPROVED** [review]
LGTM

**Pull request merged**
